Repository AY2021S2-CS2103T-W14-3/tp, pull requests merged in 2021-04, with the labels that each got.

#257 Fix prefix bug
  docs/UserGuide.md
  src/main/java/seedu/heymatez/logic/commands/AddMemberCommand.java
  src/main/java/seedu/heymatez/logic/commands/AddTaskCommand.java
  src/main/java/seedu/heymatez/logic/commands/ClearAssigneesCommand.java
  src/main/java/seedu/heymatez/logic/commands/EditMemberCommand.java
  src/main/java/seedu/heymatez/logic/commands/EditTaskCommand.java
  src/main/java/seedu/heymatez/logic/parser/CliSyntax.java
  src/main/java/seedu/heymatez/model/task/Task.java
  src/test/java/seedu/heymatez/logic/commands/ClearAssigneesCommandTest.java
  src/test/java/seedu/heymatez/logic/parser/EditMemberCommandParserTest.java
  src/test/java/seedu/heymatez/logic/parser/EditTaskCommandParserTest.java
Labels: type.Bug

#263 Add editTask duplicate name
  docs/UserGuide.md
  src/main/java/seedu/heymatez/logic/commands/EditTaskCommand.java
  src/main/java/seedu/heymatez/model/task/TaskContainsAssigneePredicate.java
  src/test/java/seedu/heymatez/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/FindMemberTasksCommandTest.java
  src/test/java/seedu/heymatez/model/task/TaskContainsAssigneePredicateTest.java
Labels: type.Bug, type.Testing

#276 Fix feature flaws and update UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/UG-examples/addMember-cmd.png
  docs/images/UG-examples/addMember-result.png
  docs/images/UG-examples/addTask-cmd.png
  docs/images/UG-examples/addTask-result.png
  docs/index.md
  src/main/java/seedu/heymatez/logic/commands/ClearAssigneesCommand.java
  src/main/java/seedu/heymatez/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/heymatez/logic/commands/DoneTaskCommand.java
  src/main/java/seedu/heymatez/logic/commands/FindByPriorityCommand.java
  src/main/java/seedu/heymatez/logic/commands/FindTasksBeforeCommand.java
  src/main/java/seedu/heymatez/logic/commands/FindTasksCommand.java
  src/main/java/seedu/heymatez/logic/commands/UndoTaskCommand.java
  src/main/java/seedu/heymatez/logic/commands/ViewTasksCommand.java
  src/main/java/seedu/heymatez/logic/commands/ViewUnassignedTasksCommand.java
  src/main/java/seedu/heymatez/logic/commands/ViewUncompletedTasksCommand.java
  src/test/java/seedu/heymatez/logic/commands/ClearAssigneesCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/DoneTaskCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/FindByPriorityCommandIntegrationTest.java
  src/test/java/seedu/heymatez/logic/commands/FindByPriorityCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/FindTasksBeforeCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/FindTasksCommandTest.java
  src/test/java/seedu/heymatez/logic/commands/UndoTaskCommandTest.java
Labels: FunctionalityFlaw

#302 Update NFR and glossary
  docs/DeveloperGuide.md
Labels: type.Documentation

#305 Rearrange ToC
  docs/UserGuide.md
Labels: type.Documentation
